create table if not exists person (
                                      id INT NOT NULL generated BY DEFAULT AS IDENTITY ,
                                      firstname VARCHAR(50),
                                      lastname VARCHAR(50),
                                       age int,
                                       occupation varchar(50)
);
create table if not exists team (
                                          id INT NOT NULL generated BY DEFAULT AS IDENTITY ,
                                          description VARCHAR(50),
                                          title VARCHAR(50),
                                           size INT
);
